config/routes.rb
Rails.application.routes.draw do
  root controller: :articles, action: :index
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id]) 
  end

  def new
    @article = Article.new
  end


  def create
    @article = Article.create(params.require(:article).permit(:title, :content))
    if @article.persisted?
      redirect_to @article, notice: "Article was created"
    else
      render 'new', notice: "Something went wrong"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<ul>
<% @articles.each do |article| %>
<li>
  <%= link_to article.title, article_path(article)%>
</li>
<%end %>

<%= link_to 'New Article', new_article_path%>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form|%>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.submit "Create Article"%>
<%end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br>
<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutCycle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <%= flash[:notice]%>
    <%end%>
    <%= yield %>
  </body>
</html>